// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace projekt_inzynierski.Server.Migrations.AchievmentDb
{
    [DbContext(typeof(AchievementsDbContext))]
    [Migration("20261004001058_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("projekt_inzynierski.Server.Achievments.Domain.Models.Achievement", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BadgeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<string>("RuleConfigJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("{}");

                    b.Property<string>("RuleKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SkillCategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Achievements");

                    b.HasData(
                        new
                        {
                            Id = "first-lesson",
                            BadgeType = "bronze",
                            Description = "Ukończ pierwszą lekcję",
                            Name = "Pierwsza lekcja!",
                            Points = 10,
                            RuleConfigJson = "{\"Threshold\":1}",
                            RuleKey = "LessonCount",
                            SkillCategory = "common"
                        },
                        new
                        {
                            Id = "5-lessons",
                            BadgeType = "silver",
                            Description = "Ukończ 5 lekcji",
                            Name = "Rozkręcamy się",
                            Points = 25,
                            RuleConfigJson = "{\"Threshold\":5}",
                            RuleKey = "LessonCount",
                            SkillCategory = "common"
                        },
                        new
                        {
                            Id = "7-day-streak",
                            BadgeType = "silver",
                            Description = "Ucz się 7 dni z rzędu",
                            Name = "Szczwany Streak",
                            Points = 40,
                            RuleConfigJson = "{\"Days\":7}",
                            RuleKey = "Streak",
                            SkillCategory = "common"
                        },
                        new
                        {
                            Id = "polyglot",
                            BadgeType = "gold",
                            Description = "Ukończ lekcje w 2 różnych językach",
                            Name = "Poliglota kodu",
                            Points = 30,
                            RuleConfigJson = "{\"DistinctLanguages\":2}",
                            RuleKey = "LanguageExplorer",
                            SkillCategory = "common"
                        },
                        new
                        {
                            Id = "task-1",
                            BadgeType = "bronze",
                            Description = "Ukończ swoje pierwsze zadanie.",
                            Name = "Pierwsze zadanie!",
                            Points = 10,
                            RuleConfigJson = "{\"Threshold\":1}",
                            RuleKey = "task-count",
                            SkillCategory = "common"
                        },
                        new
                        {
                            Id = "task-10",
                            BadgeType = "gold",
                            Description = "Ukończ 10 zadań.",
                            Name = "10 zadań zaliczonych",
                            Points = 50,
                            RuleConfigJson = "{\"Threshold\":10}",
                            RuleKey = "task-count",
                            SkillCategory = "common"
                        },
                        new
                        {
                            Id = "quiz-90",
                            BadgeType = "silver",
                            Description = "Zdobądź minimum 90% w quizie.",
                            Name = "Mistrz quizów",
                            Points = 100,
                            RuleConfigJson = "{\"MinScore\":90}",
                            RuleKey = "quiz-score",
                            SkillCategory = "common"
                        });
                });

            modelBuilder.Entity("projekt_inzynierski.Server.Achievments.Domain.Models.StudyDay", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date");

                    b.HasKey("UserId", "Day");

                    b.ToTable("StudyDays");
                });

            modelBuilder.Entity("projekt_inzynierski.Server.Achievments.Domain.Models.UserAchievement", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AchievementId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("EarnedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("UserId", "AchievementId");

                    b.HasIndex("AchievementId");

                    b.ToTable("UserAchievements");
                });

            modelBuilder.Entity("projekt_inzynierski.Server.Achievments.Domain.Models.UserProgress", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LessonId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId", "LessonId");

                    b.ToTable("UserProgress");
                });

            modelBuilder.Entity("projekt_inzynierski.Server.Achievments.Domain.Models.UserAchievement", b =>
                {
                    b.HasOne("projekt_inzynierski.Server.Achievments.Domain.Models.Achievement", "Achievement")
                        .WithMany()
                        .HasForeignKey("AchievementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Achievement");
                });
#pragma warning restore 612, 618
        }
    }
}
