// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using projekt_inzynierski.Server.Challenges.Infrastructures.Persistance;

#nullable disable

namespace projekt_inzynierski.Server.Migrations.ChallengeDb
{
    [DbContext(typeof(ChallengeDbContext))]
    partial class ChallengeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("projekt_inzynierski.Server.Challenges.Domain.Models.Badge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Badges");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImagePath = "klasy_i_obiekty_badge.png",
                            Title = "Mistrz klas"
                        },
                        new
                        {
                            Id = 2,
                            ImagePath = "pierwsze_kroki.png",
                            Title = "Pierwsze kroki"
                        },
                        new
                        {
                            Id = 3,
                            ImagePath = "for.webp",
                            Title = "Mistrz pętli"
                        },
                        new
                        {
                            Id = 4,
                            ImagePath = "pierwsze_kroki_csharp.webp",
                            Title = "Pierwsze kroki C#"
                        },
                        new
                        {
                            Id = 5,
                            ImagePath = "listy.webp",
                            Title = "Listy"
                        },
                        new
                        {
                            Id = 6,
                            ImagePath = "linq.webp",
                            Title = "Linq"
                        },
                        new
                        {
                            Id = 7,
                            ImagePath = "meotdy.jpg",
                            Title = "Metody"
                        },
                        new
                        {
                            Id = 8,
                            ImagePath = "dziedziczenie.jpg",
                            Title = "Dziedziczenie"
                        },
                        new
                        {
                            Id = 9,
                            ImagePath = "interfejsy.jpg",
                            Title = "Interfejsy"
                        },
                        new
                        {
                            Id = 10,
                            ImagePath = "pliki.png",
                            Title = "Pliki"
                        },
                        new
                        {
                            Id = 11,
                            ImagePath = "wyjatki.png",
                            Title = "Wyjatki"
                        },
                        new
                        {
                            Id = 12,
                            ImagePath = "async.png",
                            Title = "Asynchronicznosc"
                        },
                        new
                        {
                            Id = 13,
                            ImagePath = "bazy_danych.png",
                            Title = "Bazy danych"
                        },
                        new
                        {
                            Id = 14,
                            ImagePath = "test.jpg",
                            Title = "Testy jednostkowe"
                        },
                        new
                        {
                            Id = 15,
                            ImagePath = "rest_api.jpg",
                            Title = "Api Rest"
                        },
                        new
                        {
                            Id = 16,
                            ImagePath = "dependency.webp",
                            Title = "Dependency Injection"
                        },
                        new
                        {
                            Id = 17,
                            ImagePath = "events.png",
                            Title = "Delegaty i zdarzenia"
                        },
                        new
                        {
                            Id = 18,
                            ImagePath = "generyki.png",
                            Title = "Generyki"
                        });
                });

            modelBuilder.Entity("projekt_inzynierski.Server.Challenges.Domain.Models.UserBadge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BadgeId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BadgeId");

                    b.ToTable("UserBadges");
                });

            modelBuilder.Entity("projekt_inzynierski.Server.Challenges.Infrastructures.Persistance.Challenge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BadgeId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<string>("RewardDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Challenges");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BadgeId = 0,
                            Description = "Napisz prostą aplikację Hello World.",
                            Name = "Pierwsze kroki w C#",
                            Points = 50,
                            RewardDescription = "Odznaka: Początkujący",
                            Type = "Coding"
                        },
                        new
                        {
                            Id = 2,
                            BadgeId = 3,
                            Description = "Zaimplementuj program wypisujący liczby od 1 do 100.",
                            Name = "Pętla for",
                            Points = 70,
                            RewardDescription = "Odznaka: Iteracje",
                            Type = "Coding"
                        },
                        new
                        {
                            Id = 3,
                            BadgeId = 4,
                            Description = "Sprawdź, czy liczba jest parzysta lub nieparzysta.",
                            Name = "Warunki",
                            Points = 80,
                            RewardDescription = "Odznaka: Logika",
                            Type = "Coding"
                        },
                        new
                        {
                            Id = 4,
                            BadgeId = 5,
                            Description = "Stwórz listę i wypisz jej elementy.",
                            Name = "Listy",
                            Points = 100,
                            RewardDescription = "Odznaka: Kolekcje",
                            Type = "Coding"
                        },
                        new
                        {
                            Id = 5,
                            BadgeId = 7,
                            Description = "Zaimplementuj metodę obliczającą silnię.",
                            Name = "Metody",
                            Points = 120,
                            RewardDescription = "Odznaka: Rekurencja",
                            Type = "Coding"
                        },
                        new
                        {
                            Id = 6,
                            BadgeId = 1,
                            Description = "Stwórz klasę reprezentującą samochód.",
                            Name = "Klasy i obiekty",
                            Points = 150,
                            RewardDescription = "Odznaka: OOP",
                            Type = "Coding"
                        },
                        new
                        {
                            Id = 7,
                            BadgeId = 8,
                            Description = "Zaimplementuj klasę bazową i klasę dziedziczącą.",
                            Name = "Dziedziczenie",
                            Points = 200,
                            RewardDescription = "Odznaka: OOP+",
                            Type = "Coding"
                        },
                        new
                        {
                            Id = 8,
                            BadgeId = 9,
                            Description = "Stwórz interfejs i zaimplementuj go w klasie.",
                            Name = "Interfejsy",
                            Points = 250,
                            RewardDescription = "Odznaka: Architekt",
                            Type = "Coding"
                        },
                        new
                        {
                            Id = 9,
                            BadgeId = 10,
                            Description = "Napisz program zapisujący i odczytujący tekst z pliku.",
                            Name = "Pliki",
                            Points = 180,
                            RewardDescription = "Odznaka: IO",
                            Type = "Coding"
                        },
                        new
                        {
                            Id = 10,
                            BadgeId = 6,
                            Description = "Użyj LINQ do wyszukania liczb parzystych w kolekcji.",
                            Name = "LINQ podstawy",
                            Points = 220,
                            RewardDescription = "Odznaka: LINQ",
                            Type = "Coding"
                        },
                        new
                        {
                            Id = 11,
                            BadgeId = 11,
                            Description = "Napisz kod, który przechwyci i obsłuży wyjątek dzielenia przez zero.",
                            Name = "Obsługa wyjątków",
                            Points = 160,
                            RewardDescription = "Odznaka: TryCatch",
                            Type = "Coding"
                        },
                        new
                        {
                            Id = 12,
                            BadgeId = 12,
                            Description = "Zaimplementuj metodę asynchroniczną korzystającą z async/await.",
                            Name = "Asynchroniczność",
                            Points = 300,
                            RewardDescription = "Odznaka: Async",
                            Type = "Coding"
                        },
                        new
                        {
                            Id = 13,
                            BadgeId = 13,
                            Description = "Połącz się z bazą danych i odczytaj listę rekordów.",
                            Name = "Baza danych",
                            Points = 350,
                            RewardDescription = "Odznaka: DataAccess",
                            Type = "Coding"
                        },
                        new
                        {
                            Id = 14,
                            BadgeId = 14,
                            Description = "Napisz test jednostkowy dla prostej metody kalkulatora.",
                            Name = "Testy jednostkowe",
                            Points = 200,
                            RewardDescription = "Odznaka: Tester",
                            Type = "Coding"
                        },
                        new
                        {
                            Id = 15,
                            BadgeId = 15,
                            Description = "Stwórz prosty kontroler API zwracający listę obiektów JSON.",
                            Name = "API REST",
                            Points = 400,
                            RewardDescription = "Odznaka: WebDev",
                            Type = "Coding"
                        },
                        new
                        {
                            Id = 16,
                            BadgeId = 16,
                            Description = "Skonfiguruj wstrzykiwanie zależności w aplikacji ASP.NET Core.",
                            Name = "Dependency Injection",
                            Points = 450,
                            RewardDescription = "Odznaka: Architektura",
                            Type = "Coding"
                        },
                        new
                        {
                            Id = 17,
                            BadgeId = 17,
                            Description = "Utwórz delegata i zdarzenie, a następnie je wywołaj.",
                            Name = "Delegaty i zdarzenia",
                            Points = 280,
                            RewardDescription = "Odznaka: EventMaster",
                            Type = "Coding"
                        },
                        new
                        {
                            Id = 18,
                            BadgeId = 18,
                            Description = "Zaimplementuj klasę generyczną działającą dla różnych typów danych.",
                            Name = "Generics",
                            Points = 320,
                            RewardDescription = "Odznaka: Generics",
                            Type = "Coding"
                        },
                        new
                        {
                            Id = 19,
                            BadgeId = 2,
                            Description = "Napisz prostą aplikację Hello World w dowolnym języku.",
                            Name = "Pierwsze kroki",
                            Points = 10,
                            RewardDescription = "Odznaka: Początkujący",
                            Type = "Coding"
                        });
                });

            modelBuilder.Entity("projekt_inzynierski.Server.Challenges.Infrastructures.Persistance.UserChallenge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChallengeId")
                        .HasColumnType("int");

                    b.Property<bool>("Completed")
                        .HasColumnType("bit");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeId");

                    b.ToTable("UserChallenges");
                });

            modelBuilder.Entity("projekt_inzynierski.Server.Challenges.Infrastructures.Persistance.WeeklyChallenge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChallengeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeId");

                    b.ToTable("WeeklyChallenges");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChallengeId = 1
                        },
                        new
                        {
                            Id = 2,
                            ChallengeId = 2
                        },
                        new
                        {
                            Id = 3,
                            ChallengeId = 3
                        });
                });

            modelBuilder.Entity("projekt_inzynierski.Server.Challenges.Domain.Models.UserBadge", b =>
                {
                    b.HasOne("projekt_inzynierski.Server.Challenges.Domain.Models.Badge", "Badge")
                        .WithMany()
                        .HasForeignKey("BadgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Badge");
                });

            modelBuilder.Entity("projekt_inzynierski.Server.Challenges.Infrastructures.Persistance.UserChallenge", b =>
                {
                    b.HasOne("projekt_inzynierski.Server.Challenges.Infrastructures.Persistance.Challenge", "Challenge")
                        .WithMany("UserChallenges")
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Challenge");
                });

            modelBuilder.Entity("projekt_inzynierski.Server.Challenges.Infrastructures.Persistance.WeeklyChallenge", b =>
                {
                    b.HasOne("projekt_inzynierski.Server.Challenges.Infrastructures.Persistance.Challenge", "Challenge")
                        .WithMany()
                        .HasForeignKey("ChallengeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Challenge");
                });

            modelBuilder.Entity("projekt_inzynierski.Server.Challenges.Infrastructures.Persistance.Challenge", b =>
                {
                    b.Navigation("UserChallenges");
                });
#pragma warning restore 612, 618
        }
    }
}
