// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using projekt_inzynierski.Server.PremiumStore.Infrastructures.Persistance;

#nullable disable

namespace projekt_inzynierski.Server.Migrations.StoreDb
{
    [DbContext(typeof(StoreDbContext))]
    partial class StoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("projekt_inzynierski.Server.PremiumStore.Domain.Models.Avatar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Avatars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "Images/blade-runner.png",
                            IsActive = true,
                            Name = "Łowca androidów"
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "Images/clockwork-orange.jpg",
                            IsActive = true,
                            Name = "Nakręcony człowiek"
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "Images/hal-9000.png",
                            IsActive = true,
                            Name = "Nieomylne AI"
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "Images/interstellar.jpg",
                            IsActive = true,
                            Name = "Podróż w nieznane"
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "Images/moon.webp",
                            IsActive = true,
                            Name = "Nie jesteś sam"
                        },
                        new
                        {
                            Id = 6,
                            ImageUrl = "Images/tehc.jpg",
                            IsActive = true,
                            Name = "Tech"
                        },
                        new
                        {
                            Id = 7,
                            ImageUrl = "Images/trip.webp",
                            IsActive = true,
                            Name = "Memodestruktor"
                        },
                        new
                        {
                            Id = 8,
                            ImageUrl = "Images/default-avatar.jpg",
                            IsActive = true,
                            Name = "Memodestruktor"
                        },
                        new
                        {
                            Id = 9,
                            ImageUrl = "Images/water.webp",
                            IsActive = true,
                            Name = "Wodna planeta"
                        },
                        new
                        {
                            Id = 10,
                            ImageUrl = "Images/wide.webp",
                            IsActive = true,
                            Name = "Oczy zamkniete"
                        },
                        new
                        {
                            Id = 11,
                            ImageUrl = "Images/space.jpg",
                            IsActive = true,
                            Name = "W nadprzestrzen"
                        },
                        new
                        {
                            Id = 12,
                            ImageUrl = "Images/turnhal.jpg",
                            IsActive = true,
                            Name = "Wylaczenie"
                        },
                        new
                        {
                            Id = 13,
                            ImageUrl = "Images/truman.webp",
                            IsActive = true,
                            Name = "Prawda"
                        },
                        new
                        {
                            Id = 14,
                            ImageUrl = "Images/vendetta.jpg",
                            IsActive = true,
                            Name = "Prawda"
                        });
                });

            modelBuilder.Entity("projekt_inzynierski.Server.PremiumStore.Domain.Models.AvatarReward", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvatarId")
                        .HasColumnType("int");

                    b.Property<int>("RewardId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AvatarId");

                    b.ToTable("AvatarRewards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvatarId = 1,
                            RewardId = 1
                        },
                        new
                        {
                            Id = 2,
                            AvatarId = 2,
                            RewardId = 2
                        },
                        new
                        {
                            Id = 3,
                            AvatarId = 3,
                            RewardId = 3
                        },
                        new
                        {
                            Id = 4,
                            AvatarId = 4,
                            RewardId = 4
                        },
                        new
                        {
                            Id = 5,
                            AvatarId = 5,
                            RewardId = 5
                        },
                        new
                        {
                            Id = 6,
                            AvatarId = 6,
                            RewardId = 6
                        },
                        new
                        {
                            Id = 7,
                            AvatarId = 7,
                            RewardId = 7
                        },
                        new
                        {
                            Id = 8,
                            AvatarId = 9,
                            RewardId = 8
                        },
                        new
                        {
                            Id = 9,
                            AvatarId = 10,
                            RewardId = 9
                        },
                        new
                        {
                            Id = 10,
                            AvatarId = 11,
                            RewardId = 10
                        },
                        new
                        {
                            Id = 11,
                            AvatarId = 12,
                            RewardId = 11
                        },
                        new
                        {
                            Id = 12,
                            AvatarId = 13,
                            RewardId = 12
                        },
                        new
                        {
                            Id = 13,
                            AvatarId = 14,
                            RewardId = 13
                        });
                });

            modelBuilder.Entity("projekt_inzynierski.Server.PremiumStore.Domain.Models.Reward", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cost")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Rewards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cost = 150,
                            Description = "fajny obrazek",
                            ImageUrl = "Images/blade-runner.png",
                            IsActive = true,
                            Name = "Awatar",
                            Type = "Awatar"
                        },
                        new
                        {
                            Id = 2,
                            Cost = 100,
                            Description = "fajny obrazek",
                            ImageUrl = "Images/clockwork-orange.jpg",
                            IsActive = true,
                            Name = "Awatar",
                            Type = "Awatar"
                        },
                        new
                        {
                            Id = 3,
                            Cost = 100,
                            Description = "fajny obrazek",
                            ImageUrl = "Images/hal-9000.png",
                            IsActive = true,
                            Name = "Awatar",
                            Type = "Awatar"
                        },
                        new
                        {
                            Id = 4,
                            Cost = 110,
                            Description = "fajny obrazek",
                            ImageUrl = "Images/interstellar.jpg",
                            IsActive = true,
                            Name = "Awatar",
                            Type = "Awatar"
                        },
                        new
                        {
                            Id = 5,
                            Cost = 200,
                            Description = "fajny obrazek",
                            ImageUrl = "Images/moon.webp",
                            IsActive = true,
                            Name = "Awatar",
                            Type = "Awatar"
                        },
                        new
                        {
                            Id = 6,
                            Cost = 50,
                            Description = "fajny obrazek",
                            ImageUrl = "Images/tehc.jpg",
                            IsActive = true,
                            Name = "Awatar",
                            Type = "Awatar"
                        },
                        new
                        {
                            Id = 7,
                            Cost = 100,
                            Description = "fajny obrazek",
                            ImageUrl = "Images/trip.webp",
                            IsActive = true,
                            Name = "Awatar",
                            Type = "Awatar"
                        },
                        new
                        {
                            Id = 8,
                            Cost = 150,
                            Description = "fajny obrazek",
                            ImageUrl = "Images/water.webp",
                            IsActive = true,
                            Name = "Awatar",
                            Type = "Awatar"
                        },
                        new
                        {
                            Id = 9,
                            Cost = 250,
                            Description = "fajny obrazek",
                            ImageUrl = "Images/wide.webp",
                            IsActive = true,
                            Name = "Awatar",
                            Type = "Awatar"
                        },
                        new
                        {
                            Id = 10,
                            Cost = 150,
                            Description = "fajny obrazek",
                            ImageUrl = "Images/space2001.jpg",
                            IsActive = true,
                            Name = "Awatar",
                            Type = "Awatar"
                        },
                        new
                        {
                            Id = 11,
                            Cost = 350,
                            Description = "fajny obrazek",
                            ImageUrl = "Images/turnhal.jpg",
                            IsActive = true,
                            Name = "Awatar",
                            Type = "Awatar"
                        },
                        new
                        {
                            Id = 12,
                            Cost = 450,
                            Description = "fajny obrazek",
                            ImageUrl = "Images/truman.webp",
                            IsActive = true,
                            Name = "Awatar",
                            Type = "Awatar"
                        },
                        new
                        {
                            Id = 13,
                            Cost = 100,
                            Description = "fajny obrazek",
                            ImageUrl = "Images/vendetta.jpg",
                            IsActive = true,
                            Name = "Awatar",
                            Type = "Awatar"
                        },
                        new
                        {
                            Id = 14,
                            Cost = 500,
                            Description = "Zyskaj dodatkowe 100% PD",
                            ImageUrl = "Images/newPremium1.png",
                            IsActive = true,
                            Name = "Konto premium na dzień",
                            Type = "Premium1"
                        },
                        new
                        {
                            Id = 15,
                            Cost = 500,
                            Description = "Zyskaj dodatkowe 100% PD",
                            ImageUrl = "Images/newPremium7.png",
                            IsActive = true,
                            Name = "Konto premium na tydzień",
                            Type = "Premium7"
                        },
                        new
                        {
                            Id = 16,
                            Cost = 500,
                            Description = "Zyskaj dodatkowe 100% PD",
                            ImageUrl = "Images/newPremium30.png",
                            IsActive = true,
                            Name = "Konto premium na miesiąc",
                            Type = "Premium30"
                        });
                });

            modelBuilder.Entity("projekt_inzynierski.Server.PremiumStore.Domain.Models.UserAvatar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvatarId")
                        .HasColumnType("int");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UnlockedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AvatarId");

                    b.ToTable("UserAvatars");
                });

            modelBuilder.Entity("projekt_inzynierski.Server.PremiumStore.Domain.Models.UserReward", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RewardId")
                        .HasColumnType("int");

                    b.Property<Guid>("UserPublicId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RewardId");

                    b.ToTable("UserRewards");
                });

            modelBuilder.Entity("projekt_inzynierski.Server.PremiumStore.Domain.Models.AvatarReward", b =>
                {
                    b.HasOne("projekt_inzynierski.Server.PremiumStore.Domain.Models.Avatar", "Avatar")
                        .WithMany()
                        .HasForeignKey("AvatarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Avatar");
                });

            modelBuilder.Entity("projekt_inzynierski.Server.PremiumStore.Domain.Models.UserAvatar", b =>
                {
                    b.HasOne("projekt_inzynierski.Server.PremiumStore.Domain.Models.Avatar", "Avatar")
                        .WithMany("UserAvatars")
                        .HasForeignKey("AvatarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Avatar");
                });

            modelBuilder.Entity("projekt_inzynierski.Server.PremiumStore.Domain.Models.UserReward", b =>
                {
                    b.HasOne("projekt_inzynierski.Server.PremiumStore.Domain.Models.Reward", "Reward")
                        .WithMany()
                        .HasForeignKey("RewardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reward");
                });

            modelBuilder.Entity("projekt_inzynierski.Server.PremiumStore.Domain.Models.Avatar", b =>
                {
                    b.Navigation("UserAvatars");
                });
#pragma warning restore 612, 618
        }
    }
}
