// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using projekt_inzynierski.Server.Courses.Infrastructures.Persistance;

#nullable disable

namespace projekt_inzynierski.Server.Migrations.CourseDb
{
    [DbContext(typeof(CourseDbContext))]
    [Migration("20261004001113_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("projekt_inzynierski.Server.Courses.Domain.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("bit");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Podstawy programowania w języku C#: zmienne, pętle, klasy i obiekty.",
                            ImageURL = "https://contentstatic.techgig.com/photo/114568844/10-weirdest-programming-languages-youve-never-heard-of.jpg?886056",
                            IsPublic = true,
                            Language = "Polski",
                            Level = "Beginner",
                            Title = "C# dla początkujących"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Wprowadzenie do Pythona. Naucz się pisać skrypty, pracować z listami i funkcjami.",
                            ImageURL = "https://contentstatic.techgig.com/photo/114568844/10-weirdest-programming-languages-youve-never-heard-of.jpg?886056",
                            IsPublic = true,
                            Language = "Polski",
                            Level = "Beginner",
                            Title = "Python – pierwsze kroki"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Kurs skupiający się na fundamentach OOP w Javie: dziedziczenie, polimorfizm, interfejsy.",
                            ImageURL = "https://contentstatic.techgig.com/photo/114568844/10-weirdest-programming-languages-youve-never-heard-of.jpg?886056",
                            IsPublic = true,
                            Language = "Polski",
                            Level = "Intermediate",
                            Title = "Java – programowanie obiektowe"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Budowanie nowoczesnych API z użyciem ASP.NET Core i Entity Framework.",
                            ImageURL = "https://contentstatic.techgig.com/photo/114568844/10-weirdest-programming-languages-youve-never-heard-of.jpg?886056",
                            IsPublic = true,
                            Language = "Polski",
                            Level = "Intermediate",
                            Title = "ASP.NET Core – tworzenie API"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Naucz się JavaScript, DOM i podstaw Reacta, aby tworzyć dynamiczne aplikacje webowe.",
                            ImageURL = "https://contentstatic.techgig.com/photo/114568844/10-weirdest-programming-languages-youve-never-heard-of.jpg?886056",
                            IsPublic = true,
                            Language = "Polski",
                            Level = "Beginner",
                            Title = "JavaScript – od podstaw do React"
                        });
                });

            modelBuilder.Entity("projekt_inzynierski.Server.Courses.Domain.Models.FeaturedCourse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourseId")
                        .IsUnique();

                    b.ToTable("FeaturedCourses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 3
                        });
                });

            modelBuilder.Entity("projekt_inzynierski.Server.Courses.Domain.Models.UserCourse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("EvaluationResult")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Joined")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("UserId");

                    b.ToTable("UserCourses");
                });

            modelBuilder.Entity("projekt_inzynierski.Server.Courses.Domain.Models.FeaturedCourse", b =>
                {
                    b.HasOne("projekt_inzynierski.Server.Courses.Domain.Models.Course", "Course")
                        .WithOne("FeaturedCourse")
                        .HasForeignKey("projekt_inzynierski.Server.Courses.Domain.Models.FeaturedCourse", "CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("projekt_inzynierski.Server.Courses.Domain.Models.UserCourse", b =>
                {
                    b.HasOne("projekt_inzynierski.Server.Courses.Domain.Models.Course", "Course")
                        .WithMany("UserCourses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("projekt_inzynierski.Server.Courses.Domain.Models.Course", b =>
                {
                    b.Navigation("FeaturedCourse")
                        .IsRequired();

                    b.Navigation("UserCourses");
                });
#pragma warning restore 612, 618
        }
    }
}
